### PR TITLE
Add EEPROM programming capability.

### PR DESCRIPTION
**Pull request by avian2**
This change adds `-fr`/`--eeprom` command-line option that works similarly to `-f`/`--flash`. It performs an EEPROM erase, writes contents of a hex file (e.g. `.eep` file produced by Atmel Studio) into EEPPROM and verifies that the write was correct.

This command currently only works for 16k and 32k tinyAVR devices. For other
devices the correct `eeprom_*` constants in `device/device.py` need to be added first.

### CODE REVIEW

**Comment by avian2** [comment]
Hi. Are there any chances of this pull request getting merged? It would help me a lot if I didn't need to maintain a separate fork of pyupd and I think the capability of programming the EEPROM would be useful for other users as well.

If the missing EEPROM parameters for other devices is an issue in can go through the datasheets and fill them out, but unfortunately I can't test it on other than the 16 and 32k tinys.

**Comment by mraardvark** [comment]
Yupp - sorry, this has stalled up...  Right now I have little capacity to test for myself, and as a result not doing much maintenance.
FYI: I have been focusing on pymcuprog which is a proper CLI and library which is installed from pypi, can use serial port and/or a edbg debugger, and can access all memory types.  Most importantly, its tested continuously...

**Comment by avian2** [comment]
Thanks a lot for merging. I already have some code that uses pyupdi, so I'm probably going to stick with it for now.

I was not aware of pymcuprog. I'll have a look at that as well, thanks for pointing it out. Maybe it would be a good idea to put a link to pymcuprog in pyupdi's README file as a related project? It didn't seem to come up in my searches for a Python-based UPDI library.

**Comment by mraardvark** [comment]
Yes, good idea.
Right now pymcuprog is only on PyPi, but soon it will go to github as source... then I can promote it properly.
Note: if you want to try pymcuprog, the version on https://test.pypi.org/project/pymcuprog/ has a few useful fixes which are not on the production server yet

**Pull request merged**
