### PR TITLE
Add rest of AVR Dx-series

### PR DESCRIPTION
**Pull request by SpenceKonde**
The devices section has not been updated to account for newly released parts. 

This adds entries for the rest of the DA-series, the DB-series, and the as-yet-unreleased, but likely to have the same UPDI interface, DD-series.

### CODE REVIEW

**Review by janegilruud — CHANGES_REQUESTED** [review]
I think you'd better change those avr128dd's to avr64dd.

**Comment by SpenceKonde** [comment]
Oops! Fixed.

**Review by janegilruud — APPROVED** [review]
Looks good to me.

**Comment by mraardvark** [comment]
thanks folks!

**Pull request merged**
