### PR TITLE
Big performance improvement

### PR DESCRIPTION
**Pull request by MarkR42**
I've done these changes to improve the time to flash firmware.

I removed some small sleeps from the physical.py, and used the UPDI RSD flag to remove the need to receive acknowledgement bytes for every word of data written.

I also added a reset command.

I use a usb-serial adaptor; it all works for me at 115200 baud on the attiny1614 - but I haven't tried any other combination of serial port or device. I have only tested it under Linux. 

It would be really useful to test this on other serial interfaces and devices, perhaps there is some reason why these changes will fail on different devices.

I am not an expert on UPDI or attiny microcontrollers, I just read the documentation :)

### CODE REVIEW

**Comment by MarkR42** [comment]
For me, the time taken to program my device was decreased from 72 seconds, to 12 seconds.

**Comment by mraardvark** [comment]
Looks good, @MarkR42! I will give it a run when i have time (hopefully soon).
The byte-by-byte write (with echo on each) was initially a workaround for a bug caused by having one stop-bit (which was of course fixed ages ago)
Turning ACK off is a more "advanced" change, but I think it should be safe at this speed.

**Comment by mraardvark** [comment]
Works for me using tiny416 with medbg's cdc on both mac and windows.
Programming time reduced from about 14s to about 4s - nice :)

**Comment by mraardvark** [comment]
Also tested good on windows on the m4809 using its own CDC, where the gain is even more significant - I suspect due to the nedbg's CDC being optimised for data frames (not bytes).  This is about where my test coverage ends :/

**Pull request merged**
